jwt:
  secret: BvPHGM8C0ia4uOuxxqPD5DTbWC9F9TWvPStp3pb7ARo0oK2mJ3pd3YG4lxA9i8bj6OTbadwezxgeEByY
  expiration: 86400
cors:
  allowed-origins:*
spring:
  application:
    name: service-auth
server:
  port: ${PORT:0}

eureka:
  client:
    service-url:
      defaultZone: http://service-discovery:8761/eureka
  instance:
    instance-id: ${spring.application.name}:${spring.application.instance_id:${random.value}}