spring:
  application:
    name: service-websocket
server:
  port: 8085

cors:
  allowed-origins: "*"
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka
  instance:
    prefer-ip-address: true