server:
  port: 8080
spring:
  cloud:
    gateway:
      globalcors:
        corsConfigurations:
          '[/**]':
            allowedOrigins: "*"
            allowedMethods:
              - GET
              - POST
              - DELETE
              - PUT
  application:
    name: api-gateway

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka
      register-with-eureka: false
  instance:
    preferIpAddress: true

management:
  endpoints:
    web:
      cors:
        allowed-origins: "http://localhost:5500"
        allowedMethods:
          - GET
          - POST
          - PUT
          - DELETE
      exposure:
        include: "gateway"

logging:
  level:
    org.springframework.cloud.gateway: DEBUG
    reactor.netty.http.client: DEBUG
